### ISSUE TITLE
Update Solidity backend

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#108]
### What is wrong?

We are using a version of solc-rust that compiles with Solidity version 0.6.2, we should instead be using Solidity version 0.7.4 or maybe even the 0.8.x preview.

See [this](https://github.com/axic/solc-rust/pull/2) for relevant info.

### How can it be fixed

Upgrade the Solidity submodule in solc-rust and and fix any issues that arise.

**Comment by sbillig** [comment]
It's time for another update. We're missing support for the new basefee opcode.
