### ISSUE TITLE
Create a Fe Book

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#121]
### What is wrong?

Most Rust projects use [mdBook](https://github.com/rust-lang/mdBook) to build their docs. We should do the same.

### How can it be fixed

- [ ] move the existing spec and docs into a new folder named *book*
- [ ] add mdBook to our build
- [ ] make sure the book looks ok

**Comment by cburgdorf** [comment]
This happend a while ago and is live here: http://fe.ethereum.org/docs/index.html
