### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#144]
## Regular releases

I've thought a bit about release planning and would like to propose that we follow a fixed regular release schedule. I believe this comes with a number of benefits:

- Having regular releases forces us to focus stronger on **what is important** for the next release
- Releases are a good indicator of progress
- Regular releases can increase community engagement
- Regular releases decrease risk of failure and disappointment

There's a lot written on this topic and I think the general consensus is that regular releases are a good thing and result in better software.

### A monthly schedule

So, I went on thinking about *how regular* we might want to ship a new release. My current thinking is that *every month* would make a nice target. Anything more frequent might be prone to fail especially with a team as small as hours. A release every two weeks might get easily disrupted by holidays etc whereas a release every months sounds doable on a consistent basis.

### Release naming scheme

This had me thinking about a release naming scheme. Of course we are going to follow [semver](https://semver.org/) but it might be nice to give each release a name just liking Ubuntu does (e.g. Ubuntu 20.10 Groovy Gorilla). Trinity does the same and each release highlights a woman in science.

One thing that resonates with me is trying to connect to our name Fe. There are more than 5000 known minerals in the word that might make good use for release names. We could even combine that with the months of the release and arrive at something like:

- January Jade
- February Ferrum
- March Minium
- April Amethyst 
- ...

We could also just follow the alphabet instead of matching the first letter of the months. I just like the idea of using minerals as release names. Wikipedia has a good sorted list of minerals: https://en.wikipedia.org/wiki/List_of_minerals

### Release planning

We can create milestones for every release of the year ahead of schedule but we should at a minimum always have the milestone for the upcoming release and the one after that on GitHub. That is so that we can move issues from one release to the next if the window is closing and we realize an issue has to be moved to the next milestone.

At the beginning of each months we spend some time to assign issues to the upcoming release miestone. This will help us to increase focus on what is important to achieve next.

### Semver

We are expected to follow semver. While semver *allows* to stick to a version like `0.1.0` and only increase a pre-release suffix e.g. `0.1.0-alpha.1`, `0.1.0-alpha.2`, `0.1.0-alpha.3` I'm personally not a fan because semver defines everything to the righthand side of the dash as just meaningless alphanumeric text. It could also be `0.1.0-y7pRR.8.3.J`. Therefore, I suggest we use the individual components of the semver scheme right from the beginning and just attach `-alpha` to it until things stabilize. So releases would look like `0.1.0-alpha`, `0.2.0-alpha`, `0.2.1-alpha`. Both are valid uses of semver but I like the latter approach a whole lot more.

**Comment by cburgdorf** [comment]
Let me summarize what we discussed offline. We are going with monthly releases, picking release names with names from minerals starting with A, and going through the alphabet. According to that I will rename the milestone for our first release to `January Release: 0.1.0 Amethyst`

**Comment by g-r-a-n-t** [comment]
I've also changed the February mineral to something starting with a "B".

https://en.wikipedia.org/wiki/Borax

**Comment by cburgdorf** [comment]
Ah yes, thanks.

**Comment by sbillig** [comment]
We've been following this release schedule for a while now. Closing.
