### ISSUE TITLE
Error improvements (multiple errors and consistent formatting)

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#147]
### What is wrong?

1. We currently return only the first error encountered during analysis of a Fe program. We should instead collect as many errors as we can and return them to the user.

2. We also have inconsistent formatting between semantic and parser errors. Both of these errors should have the same user format to provide a consistent experience. 

### How can it be fixed

1. Add a new error kind `Many` or something that contains a vector of semantic errors. Anytime we encounter a situation where we analyze multiple branches of code, we should include the returned errors (if any) in this new kind.

2. See if we can share error formatting code.

**Comment by cburgdorf** [comment]
This landed
