### ISSUE TITLE
Support underscores in numeric literals

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#149]
### Abstract

We should support underscores `_` in numeric literals so that `1000000000000000000` can be written in the more readable form of  `1_000_000_000_000_000_000`.

### Motivation

Fe is intended to be used in smart contract development and variables and constants holding large numerals is a very well expected normal use case.  Especially since many variables are going to represent `Wei` and e.g. `1_000_000_000_000_000_000` Wei represent `1` Ether.

**Comment by plv** [comment]
Hi, does this still need doing? Happy to take it on.

**Comment by cburgdorf** [comment]
@plv yes, feel free to take it!

**Comment by voith** [comment]
@plv are you still working on this? If not can I take this up?

**Comment by plv** [comment]
@voith  Sorry for the late response -- I never got around to this. Feel free to take it :)

**Comment by Jake-Steck** [comment]
@plv Hi, does this still need help? I am here if so.

**Comment by cburgdorf** [comment]
@Jake-Steck it doesn't seem that anyone is currently actively working on it so feel free to make it yours :)

**Comment by voith** [comment]
@Jake-Steck I never got started on this. So feel free to take it.
