### ISSUE TITLE
Add runtime conversion methods for integer types

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#165]
### What is wrong?

Currently, there is no built-in way in Fe to take a variable of e.g. type `u16` and turn it into an `u8` which depending on the actual value of the variable might or might not fit into an `u8` without changing its value.

Often languages allow a way to *cast* a value from one type to another which is usually away to tell the compiler *"Step away, I know what I'm doing here. Take this `x` and just treat it as `<other-type>` because I know that the underlying memory does actually represent that `<other-type>`*" One scenario where this commonly happens is when we work with serialized data for which by nature the developer has more insight than the compiler. Obviously these casts may fail and bring programs to crash.

Fe doesn't currently allow *casting* values in that fashion and it is unlikely that it will since it aims to be a very safe language with few chances of unexpected errors.

Fe should only allow type casting for situations where it can guarantee the outcome. For now it only allows it to happen with literals such as `u8(1)` because it can perform compile time checks on the literal (e.g. `1`) and reject anything that won't fit into the given type. In the future we might go beyond literals and allow things like `u16(x)` in scenarios where we know that `x` is of a type that fits into an `u16`.

#### Runtime conversions

To deal with scenarios where we can not just *silence* the compiler to treat some variable as another type because we might have to perform modifications to the value, we should use *runtime conversions*.

E.g. we might introduce methods on numeric types that let us convert from one type to another. 

Example:

```
def foo(val: u16):
    x: u8 = val.to_u8()
```

In this case `val` would be *converted* into an `u8` which means we are performing defined conversion rule such as truncating the 8 most significant bits.

**Comment by sbillig** [comment]
Implemented in #576
