### ISSUE TITLE
impl blocks for structs and enums

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#166]
### `impl` blocks for structs and enums

Recently I have been thinking about `impl` blocks for structs and enums. Fe doesn't have structs or enums yet but it seems we are in favor of them and I was wondering if a.) we would allow to declare methods on those and if yes would we b.) use `impl` blocks to define such methods outside of the actual struct/enum definition or inside.

I was thinking if there was a good reason for us to define methods outside of the struct/enum definiton in an `impl` block other than the blunt "I want Fe to be like Rust" kind of argument.

I think I have a compelling reason for it and I wanted to lay it out here. 

Suppose we are building a system with multiple contracts. Let's say that these contracts share a common struct `Rectangle`.

```
struct Rectangle:
    with: u256
    height: u256
```

Now let's imagine that we would like to define a `can_hold` method for `Rectangle` to check whether another `Rectangle` instance would fit inter ours.

Using an `impl` block that might look like this:

```
impl Rectangle:

    def can_hold(self, other: Rectangle) -> bool:
        self.width > other.width && self.height > other.height
```

Now imagine that contract `a` uses code such as `rect_foo.can_hold(rect_bar)` but all the other contracts in the system do still use the `Rectangle` struct but they don't use any of such methods.

I would argue that with the `impl` block being something separate (potentially even in a separate file) it becomes much easier to ensure that all contracts hold code to work with `Rectangle` but only contract `a` holds that extra code of the `can_hold` method.

If we instead mangle fields and methods together as seen in the following example code, it may become much harder to separate it from the generated code.

```
struct Rectangle:
    with: u256
    height: u256

    def can_hold(self, other: Rectangle) -> bool:
        self.width > other.width && self.height > other.height
```

The counter argument would be that the YUL optimizer probably would ensure to remove `can_hold` from all contracts that doesn't actually use it so my whole point may be moot. :joy:

**Comment by g-r-a-n-t** [comment]
The Yul optimizer should get rid of any functions that aren't called, so I don't think we need to worry about contract sizes. Also, Rust disallows implementations on external types for design reasons, so I think we should follow suit.

> But we can’t implement external traits on external types. For example, we can’t implement the Display trait on Vec<T> within our aggregator crate, because Display and Vec<T> are defined in the standard library and aren’t local to our aggregator crate. This restriction is part of a property of programs called coherence, and more specifically the orphan rule, so named because the parent type is not present. This rule ensures that other people’s code can’t break your code and vice versa. Without the rule, two crates could implement the same trait for the same type, and Rust wouldn’t know which implementation to use.

from: https://doc.rust-lang.org/book/ch10-02-traits.html#implementing-a-trait-on-a-type

I personally like the look of the last example you've provided

```
struct Rectangle:
    with: u256
    height: u256

    def can_hold(self, other: Rectangle) -> bool:
        self.width > other.width && self.height > other.height
```

since it's consistent with the syntax of contracts and compact.

If we decide, however, that we should provided support for traits or something like traits, then I'd be for `impl` blocks.

**Comment by sbillig** [comment]
Support for struct functions was added in #577
