### ISSUE TITLE
Remove the mentions of Vyper in the README

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/fe#176]
### What is wrong?
Some people are still confused if Fe is related to Vyper, I think a potential reason why is because the README mentions Vyper a lot in defining what Fe is. Politics aside, it just reads poorly to have a bunch of statements that basically say "it's like this thing, but different", and it would be more useful to the reader to understand what Fe is without having to understand the context under how the project got created (although we do appreciate the free marketing!)

### How can it be fixed
Remove references to "Vyper" (or `rust-vyper`) and define Fe by itself: what it does, what are its principles, what makes it a good choice, etc. This will be better for users to read through rather than to see it as a derivative of another project, which will only confuse them more.

For context, Vyper had a lot of negative references to Solidity at one point early in it's existence, but we decided to remove many of those references and focus on what the language does well vs. comparing it to something else. In the long run, this helped the language differentiate itself from Solidity, and was friendlier to newcomers who may not have understood the references or where Vyper was their first experience with Ethereum smart contract development.

**Comment by cburgdorf** [comment]
Yeah, our Readme feels outdated at this point. And as we are aiming for our first release this months this is something we should fix as soon as possible. Thanks for pointing it out. We'll make sure to remove references to Vyper. As you said, they aren't really helpful to understand what the language is about.

**Comment by cburgdorf** [comment]
@fubuloubu the new Readme landed. If you find anything else that you think isn't quite right please let me know.

**Comment by fubuloubu** [comment]
Reads much better now!
