### ISSUE TITLE
Tuples with base types

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#187]
### What is wrong?

We do not support non-empty tuples.

### How can it be fixed

For now it should be alright to just support tuples that contain only base types.

This issue may need to be broken up into smaller pieces, as I think tuple support will be a bit complicated.

**Comment by cburgdorf** [comment]
In #205 we talked about implementing Tuples through a "desugaring" pass

>For instance, a Tuple of type `(u8, string100)` may just be syntactic sugar such a struct:

```
struct $tuple_u8_string100:
    0: u8
    1: string100
```

I was thinking that if an actual desugaring pass that takes *Fe* and produces *Fe'* isn't feasible in the short term than we could still implement Tuples on top of structs without an actual desugaring pass.

Basically, I think, all we would need is a separate version of this that creates structs from tuple definitions and assigns them a name according to a deterministic formular (such as `tuple_u8_string100` for `(u8, string100)`)

https://github.com/ethereum/fe/blob/573606773aeea0d6ddeaa843cae249bb0da21462/analyzer/src/traversal/structs.rs#L17-L36

I think this could be implemented quite easily and it would also be very easy to replace that with an actual desugaring pass later on.

**Comment by g-r-a-n-t** [comment]
I'm removing this from the Uniswap milestone, as it is no longer required for it.

**Comment by sbillig** [comment]
Closed by #352
