### ISSUE TITLE
yultsur / solc-rust

### ISSUE THREAD

**Issue by axic** [ethereum/fe#2]
I see in the README that "This implementation targets the YUL IR used by and developed for Solidity". Do you have anything in mind yet how to do that?

Incidentally we have two projects which could be of help to you:
- [yultsur](https://github.com/axic/yultsur) - a library for the Yul AST, to parse, print and have a programmatic builder
- [solc-rust](https://github.com/axic/solc-rust) - Rust bindings for the Solidity compiler

They didn't receive too much attention in the past year due to lack of time and lack of users, but if you project would utilize them that would mean it makes sense to keep them maintained.

**Comment by davesque** [comment]
Hey @axic .  Thanks so much for reaching out!

My initial thoughts on using YUL were to do string building of YUL source and then just pass it off to the Solidity compiler.  Obviously, the string building is a dirty hack and would have been mostly intended just to prove the overall concept more quickly.  But I've begun to think I should at least have a set of Rust AST types for YUL.  Then I would just convert the Vyper AST into a YUL AST and do code generation from there.  The work I'm seeing currently in the yultsur library seems like it would be really useful for that.  Perhaps I could avoid the code generation entirely if solc-rust works well enough.

Eventually, my long term vision for things was to have a YUL compiler written entirely in Rust.  There are a couple reason I had for this idea:
* C++ is kind of clunky and old and I don't much enjoy using it :)
* Rust readily compiles to WASM which opens up some interesting possibilities in terms of portability of a compiler written in Rust.  In the near term, this could facilitate automatic verification of contracts, in-browser compilation of Vyper contracts, etc.  In the long term, maybe something interesting could even happen with regard to eWASM and pre-compiled contracts.

Anyway, thanks for pointing those libraries out to me.  I think they'll definitely come in handy and I wouldn't mind if they weren't abandoned.  I might even be interesting in contributing to them as a result of the work I'm doing on rust-vyper.  Would love to chat more at devcon about all of this.
