### ISSUE TITLE
Fully implement expression mapping

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#21]
The following expressions need to be mapped to Yul:

- [ ] Ternary
- [ ] BoolOperation
- [x] BinOperation
- [ ] UnaryOperation
- [x] CompOperation
- [ ] Call
- [ ] List
- [ ] ListComp
- [ ] Tuple
- [ ] Str
- [ ] Ellipsis

Attempting to compile a contract that includes one of these expressions will give rise to an `unimplemented` error.

**Todo:**
Replace each branch in this [statement](https://github.com/ethereum/rust-vyper/blob/a7232b1522b1858f1372b35fbec3fd678029d38c/compiler/src/yul/mappers/expressions.rs#L29) with an appropriate call to a new mapping function that returns an [`ExtExpression`](https://github.com/ethereum/rust-vyper/blob/a7232b1522b1858f1372b35fbec3fd678029d38c/compiler/src/yul/mappers/expressions.rs#L22) result.

**Comment by sbillig** [comment]
Ellipsis and ListComp have been cut (but could be revived later, if needed); the rest have been implemented.
