### ISSUE TITLE
Yul compilation failed: Variable name $sum already taken in this scope.

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#223]
Compiling this file:

```
contract Foo:
    pub def bar() -> u256:
        sum: u256 = 0
        sum: u256 = 0
        return sum
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"DeclarationError: Variable name $sum already taken in this scope.\n --> input.yul:1:192:\n  |\n1 |  ... ar() -> return_val { let $sum := 0 let $sum := 0 { return_val := $sum leave } } fun ...\n  |                                         ^^^^^^^^^^^^^\n\n","message":"Variable name $sum already taken in this scope.","severity":"error","sourceLocation":{"end":204,"file":"input.yul","start":191},"type":"DeclarationError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by cburgdorf** [comment]
I think we need to refactor this method:

https://github.com/ethereum/fe/blob/7443ac2ea8db6de161fa041a821dde8de2ec8047/analyzer/src/namespace/scopes.rs#L268-L270

We are currently ignoring the return value of `insert` which would indicate us if the variable already exists in the current scope (in which case we should return the appropriate error)

**Comment by lykhonis** [comment]
Would `add_function` also fall under same scenario? It seems it also just adds new function into the same scope without a check for existing one. What should be the outcome? A bool or some error result?

**Comment by cburgdorf** [comment]
>Would `add_function` also fall under same scenario?

I believe it should (unless we would plan for function overloading which I doubt we would ever want)

>A bool or some error result?

The bad thing about returning a `bool` is that it can easily be ignored (as seen with the `bool` that `insert` returns). I think we should add a new `ErrorKind`, something like `DuplicateDefinition` and then return a `Result<(), SemanticError>`.

**Comment by agroce** [comment]
Fuzzer just found the dup function variant; will run on the new code soon to make sure all this is fixed, but it looks straightforward enough.
