### ISSUE TITLE
Fully implement function statement mapping.

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#23]
The following function statements need to be mapped to Yul:

- [x] AugAssign
- [ ] For
- [ ] While
- [ ] If
- [ ] Assert
- [ ] Expr
- [ ] Pass
- [ ] Break
- [ ] Continue
- [ ] Revert

Attempting to compile a contract that includes one of these statements will give rise to an `unimplemented` error.

**Todo:**
Replace each branch in this [statement](https://github.com/g-r-a-n-t/rust-vyper/blob/b2504d074c5f5bd2683a602e86ae75da6b1ec117/compiler/src/yul/mappers/functions.rs#L122) with a call to a new mapping function that returns a `yul::Statement` result.

**Comment by sbillig** [comment]
I believe all of these have been implemented.
