### ISSUE TITLE
Hang compiling invalid contract with _before_token_transfer(sender, recipient, amount)

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#233]
Compiling the attached file hangs fe.

[transferhang.zip](https://github.com/ethereum/fe/files/5933644/transferhang.zip)

backtrace I get in rust-gdb isn't very helpful, but looks like maybe symbols are missing?

```
Program received signal SIGINT, Interrupt.
0x000055a91e9d6f5e in regex::backtrack::Bounded<I>::backtrack ()
(gdb) bt
#0  0x000055a91e9d6f5e in regex::backtrack::Bounded<I>::backtrack ()
#1  0x000055a91e9d672f in regex::backtrack::Bounded<I>::exec ()
#2  0x000055a91ea0dd64 in regex::exec::ExecNoSync::exec_nfa ()
#3  0x00000000000005b4 in ?? ()
#4  0x0000000000000000 in ?? ()
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by sbillig** [comment]
This doesn't hang anymore. Seems like it was an issue with the old parser.

**Comment by sbillig** [comment]
(It now fails immediately with an "unexpected token" error)
