### ISSUE TITLE
Enforce key value syntax to initialize structs

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#234]
### What is wrong?

When #203 lands, we'll have basic support for structs.

```
struct House:
    price: u256
    size: u256
    vacant: bool

contract City:

    pub def get_price() -> u256:
        building: House = House(300, 500, true)

        assert building.size == 500
        assert building.price == 300
        assert building.vacant

        return building.price
```

The current syntax for initializing structs is the same as for all function invocations (e.g. `House(300, 500, true)`) in the example above.

I believe for better clarity struct initialization should look like one of these:

A. `House(size=500, price=300, vacant=true)`

or B.  `House(size:500, price:300, vacant:true)`

### How can it be fixed

1. Settle on syntax

2. Make modifications to the parser

**Comment by cburgdorf** [comment]
@g-r-a-n-t What is your opinion here? I think we should go with `House(size=500, price=300, vacant=true)` and forbid the current syntax (`House(500, 300, true)`)

**Comment by g-r-a-n-t** [comment]
I vote **A**.
