### ISSUE TITLE
Optimize access of struct fields in storage

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#249]
### What is wrong?

When accessing struct fields in storage we are currently calculating storage pointers in YUL (which the optimizer doesn't optimize away)

https://github.com/ethereum/fe/blob/fa7c3c1bbd120959a3a474190b4a73eee623072f/compiler/src/yul/mappers/expressions.rs#L472

### How can it be fixed

1. We could pre-calculate them
2. Alternatively we might end up optimizing this another way as soon as we start storing structs tightly packed

**Comment by Y-Nak** [comment]
will be resolved in #676 
Both 1. and 2. will be realized.
