### ISSUE TITLE
Visibility of subsequently defined contracts.

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#283]
### What is wrong?

If two contracts are defined in a module, only the second contract can see the interface of the first.

e.g.

```python
# can't see Bar
contract Foo:
   ...

# can see Foo
contract Bar:
   ...
```

### How can it be fixed

Do the same thing that we're doing for function analysis.

see #90

**Comment by cburgdorf** [comment]
I started working on this
