### ISSUE TITLE
Parser efficiency/semantic improvements

### ISSUE THREAD

**Issue by davesque** [ethereum/fe#3]
The current use of parser combinators provided by the [nom](https://github.com/Geal/nom) library means that parsing is an `O(n^2)` time and `O(n)` space operation.  Also, the lack of support for left-recursion means that parsing of things like `x + y + z` (where evaluation should happen from left-to-right) is a bit awkward and requires some post-processing.  For example, parsing the above string with a grammar definition like this:
```
const_expr: const_term ('+' const_term)*
```
Means that the parse tree comes out in the wrong order and needs some post-processing before the order of evaluation is faithfully represented.  This problem does not exist with a left-recursive grammar:
```
const_expr: const_expr '+' const_term | const_term
```
See [here](https://medium.com/@gvanrossum_83706/left-recursive-peg-grammars-65dab3c580e1) for more details.

Future versions of this project should modify existing parser combinators to memoize results and possibly also use memoization functionality to provide support for left-recursion (as is also described [here](https://medium.com/@gvanrossum_83706/left-recursive-peg-grammars-65dab3c580e1)).  Or, an entirely different parsing library could be used that supports those features out of the box.

**Comment by sbillig** [comment]
Closed by #346
