### ISSUE TITLE
[WIP] Road to production

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#303]
# Reflections on Fe's path to production

Fe is still under rapid development and all our releases are marked as *alpha* and we **strongly** discourage usage beyond just *tinkering* with the language.

This document is meant to reflect on *minimal* requirements that Fe needs to meet to enter the next stage where we would say: *It may not be the most pretty language, nor the most efficient language but you are encouraged to give it a try nonetheless.*

At that stage of development we can cut a first release that would act as our minimal valuable product (MVP).

## Non goals

Let's first reflect on all the things that are **NOT** needed to hit our MVP target.

### Language stability

For the MVP, we do not have to care about breaking changes **at all**. Our MPV release will still be a `0.x.x` release and to cite [semver.org](https://semver.org/#spec-item-4) on that:

>major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

To give a concrete example, we do currently only support fixed size string types that syntactically are written as `stringN` where `N` can take any `u32` value such as `string100`, `string4711` etc. We aren't dead set on this and believe that in the future, when we have something like [Rust's const generic](https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md) these types may become entirely obsolete. We shouldn't care about these breaking changes (or any other breaking changes) for the MVP at all.

### Feature completeness

Language development is a marathon, not a sprint. It is reasonable to assume we will still be lacking many wanted features long before we reach a point where the language *can* be used anyway. Missing features shouldn't keep us from shipping our first non-alpha version unless they are so essential that one wouldn't be able to use the language for anything. But since we already have a working version of [Uniswap V2 implemented in Fe](https://github.com/ethereum/fe/blob/master/compiler/tests/demo_uniswap.rs) it could be argued that we are already past that stage.

### Gas efficiency

Although it is a stated goal of Fe to produce efficient byte code, we shouldn't care too much about gas efficiency for our first MVP release. We do get some efficiency improvements for free via the YUL optimizer that we are using. We can tackle gas efficiency at later stages in development and should just make it very explicit that this would not be a goal for the MVP release.

## Actual goals

Let's get to the list of things that we **do** have to care about for our first MVP.

### Best effort to not produce unsound code

One of the most important things that we **do** need to get right for our MVP is to ensure the compiler doesn't produce unsound bytecode. In other words, the analyzer should reject any code that violates certain conditions (set by the language spec) such as calling a function with parameters that have the wrong type. Not rejecting code that should be rejected can lead to tragic errors especially in an environment that is all about securing billions of money.

### Reasonable testing effort

It goes hand in hand with the previous point that we need to make a reasonable testing effort to achieve a high level of confidence in the compiler. This includes:

- Unit tests
- Integration Tests
- Fuzzing
  - General compiler fuzzing
  - Differential contract fuzzing 

Since we are also implementing all the Uniswap V2 contracts in Fe we could also go as far as running the Uniswap test suite against the Fe implementation of the contracts.

### Basic Developer UX

We need to make an effort to actually use Fe to deploy code and make sure there aren't any dev UX show stopper left that make it impractical to develop and deploy in Fe. This may entail doing some integrations with existing tooling or mitigating known issues through documentation.

### Documentation & Spec

We should make an effort to get the specification up to date and have at least some guides / tutorials on how to get started with Fe.

### Pre-audit

Our current thinking is that we would start getting an audit firm on board to work with us as soon as we are confident that we have fixed all obvious unsoundness or other important bugs and feel reasonable confident about Fe's safety. This doesn't necessarily entail getting a full audit at that stage but help us to identify areas that might need extra attention.

It should be pointed out that we do already gain some trust simply through the fact that our last stage of compilation is YUL -> bytecode [which is the same for solidity](https://forum.soliditylang.org/t/solidity-team-ama-2-on-wed-10th-of-march-2021/152/11).

## Timeline

We are reasonable confident that we will deliver on our first MVP release in Q3/Q4 2021.

**Comment by cburgdorf** [comment]
Add specifictation

**Comment by g-r-a-n-t** [comment]
Here's a link to all [mvp-required](https://github.com/ethereum/fe/issues?q=is%3Aopen+is%3Aissue+label%3A%22flag%3A+mvp-required%22) issues for convenience.

**Comment by cburgdorf** [comment]
This landed as a blog post: https://snakecharmers.ethereum.org/fes-path-to-production/
