### ISSUE TITLE
Properly validate static strings

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#329]
### What is wrong?

We do currently not properly validate static strings which in theory can lead to severe consequences when we not reject certain characters. In practice YUL will catch and reject them for us but we want to make sure that we catch these errors early on and reject them properly.

Related bug report: #220

### How can it be fixed

We should look into what Solidity is doing. The majority of the validations should probably be taken care of at the parsing stage already.

Related: https://github.com/ethereum/solidity/blob/88d340f279f6c338dde6b2d551fe5aba547a2ae0/liblangutil/Scanner.cpp#L773-L910

**Comment by sbillig** [comment]
The new parser will emit an error if there are invalid escape sequences (via https://crates.io/crates/unescape), but doesn't check for any other illegal characters (yet).

**Comment by cburgdorf** [comment]
I just stumbled over this again and noticed that Solidity and YUL currently only allow the printable ASCII characters to be used in static strings. So using something like the German character `ä` will currently lead to a crash at the YUL stage.

Longer term we should figure out a way to *safely* support non ascii characters and the Solidity team already circulated some ideas in [this thread](https://github.com/ethereum/solidity/issues/10607#issuecomment-745349889)

For now, restricting to the printable ascii characters should be easy to implement so I put that on the current milestone.

**Comment by cameel** [comment]
> I just stumbled over this again and noticed that Solidity and YUL currently only allow the printable ASCII characters to be used in static strings.

That's true in Yul. In Solidity though unicode characters are allowed in special [unicode literals](https://docs.soliditylang.org/en/latest/types.html#unicode-literals).

That's just syntactic sugar though (there's always an equivalent plain string with escapes) and the weird corner cases that are possible with unicode are always a headache so limiting the character set and then only selectively allowing unicode chars in some places sounds like a good idea in my opinion.

**Comment by cburgdorf** [comment]
@cameel Ah, thanks for the clarification. I hadn't noticed the unicode literals!
