### ISSUE TITLE
Allow hexadecimal/octal/binary numeric literals

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#333]
### What is wrong?

Currently, the analyzer doesn't allow numeric literal representation other than decimal. This is inconsistent with both Rust and Python specifications.

### How can it be fixed

1. Allow the representations in `analyzer`.
2. Normalize the representations for `Yul`, I think this would be done in lowering pass.

**Comment by g-r-a-n-t** [comment]
Thanks for the issue @Y-Nak, we definitely want this.

> Normalize the representations for Yul, I think this would be done in lowering pass.

Normalizing might be at odds with Yul readability. I'm not sure if this should be a deal breaker, though.

From the [docs](https://docs.soliditylang.org/en/v0.8.3/yul.html#motivation-and-high-level-description): *"Programs written in Yul should be readable, even if the code is generated by a compiler from Solidity or another high-level language."*

**Comment by g-r-a-n-t** [comment]
Yul supports hex, so I'm wondering if we want retain that representation in the Yul contracts, since certain expressions are easier to read with a given representation. As far as octal and binary go, we would definitely want to normalize that to hex in the lowering pass.

**Comment by g-r-a-n-t** [comment]
That would be great :slightly_smiling_face:. We just need to wait for https://github.com/ethereum/fe/pull/338 to get merged before this can be fully implemented, but that should be all.

**Comment by Y-Nak** [comment]
The simplest and most beautiful way to implement this is adding the representation kind to AST in parsing pass, so I'd like to wait for #346.
