### ISSUE TITLE
Differential Contract Testing / Fuzzing

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#354]
### What is wrong?

It would be really valuable for us to perform differential contract testing to find compiler bugs and build up trust in the compiler.

For example, we would take the FE ERC20 implementation and the Zeppelin ERC20 contract and fuzz them both with the same input. If the contract states or output differ between the contracts, then we’ve found a bug.

#### Useful links:

- [Differential Testing](https://en.wikipedia.org/wiki/Differential_testing)
- [Rust Fuzz Book](https://rust-fuzz.github.io/book/introduction.html)
- [Differential Fuzzer for Ethereum 2.0](https://github.com/sigp/beacon-fuzz)

**Comment by cburgdorf** [comment]
Loosely related to https://github.com/ethereum/fe/issues/309

**Comment by cburgdorf** [comment]
@satyamakgec I can not assign this to you yet (I'll follow up on Github team membership) so just commenting to raise awareness.

**Comment by satyamakgec** [comment]
@cburgdorf Yeah that I am waiting for the access and all stuff.

**Comment by Rsalyme** [comment]
@cburgdorf Do you still need help with this?

**Comment by cburgdorf** [comment]
Hi @Rsalyme 

This issue can be closed because we generally have the infrastructure and run certain differential contract fuzzing tests. However, if you like to add some more you'd be welcome to contribute.

1. Here is where the contracts are: https://github.com/ethereum/fe/tree/master/crates/test-files/fixtures/differential (notice they are written in Fe and Solidity)
2. They are executed here: https://github.com/ethereum/fe/blob/master/crates/tests/src/differential.rs#L177-L262 Notice that we also report gas cost differences and error out if gas usage regresses
3. These tests are very expensive to run but we run them every hour and they have caught bugs and regressions in the past. https://github.com/ethereum/fe/actions/workflows/expensive.yml
