### ISSUE TITLE
Named arguments

### ISSUE THREAD

**Issue by sbillig** [ethereum/fe#397]
### What is wrong?

The parser and ast support python-style named arguments, but the names aren't checked in the rest of the compiler.
```
def f(x: u256, y: u256) -> u256:
  return x - y

def g() -> u256:
  return self.f(y=10, a=5)  # same as f(10, 5), so x = 10, y = 5
```

Furthermore, functions can be called without specifying argument names, which can be a source of bugs.
```
def _update(balance0: u256, balance1: u256, reserve0: u256, reserve1: u256):
   ...
self._update(token0.balanceOf(self.address), self.reserve0, token1.balanceOf(self.address), self.reserve1)
```

### How can it be fixed

I think we should require argument names, and require that arguments always be provided in the correct order. I also think we should use `:` instead of `=`. Eg `self.transfer(from: me, to: you)`

We could consider adopting swift's syntax and semantics here https://docs.swift.org/swift-book/LanguageGuide/Functions.html

In swift, function parameters have labels (which default to the parameter name). Labels must be included when calling the function, and arguments must be provided in the correct order. In cases where labels aren't warranted, they can be disabled for a given parameter.

Default case:
```
def transfer(sender: address, recipient: address):
  ...
self.transfer(sender: me, recipient: you)
```

Specify different label names, so calls are convenient but the function body can use long names (which can change without breaking the calling code):
```
def transfer(from sender_addr: address, to recipient_addr: address):
  ...
self.transfer(from: me, to: you)
```

Disable labels:
```
def max(_ val1: u256, _ val2: u256):
  ...
self.max(x, y) # instead of self.max(val1: x, val2: y)
```
note that some args can have labels while others don't

```
def new_account(_ addr: address, balance: u256 = 0):
  ...
new_account(sender)
new_account(sender, balance: 100)

```

**Comment by g-r-a-n-t** [comment]
I like this. It makes things alot easier to read.

For something like this

```
send_1_dai(my_friend)
```

it's pretty clear what the parameter is, but for something like this

```
MyContract::create2(42, 26)
```

I would need to look at the docs, which is annoying.

```
MyContract::create2(value: 42, seed: 26)
```

is much easier to read.

The separation of internal and external names is quite important for this, as things often need to be more verbose on the inside.

```
def send_double_their_dai(to to_addr: address):
  to_balance: u256 = dai_contract.balanceOf(to_addr) 
  send_many_dai(to: to_addr, amount: to_balance * 2)
```

---

I think for simpler functions, this might be overkill, but it's all small price to pay in the grand scheme of things

**Comment by g-r-a-n-t** [comment]
I'm also on board with switching to `:` instead of using `=`.

**Comment by cburgdorf** [comment]
If you have something like this
```
def transfer(from sender_addr: address, to recipient_addr: address):
  ...
```

Wouldn't it be reasonable to not require the labels if the variable name matches the argument name. E.g if I use `from` and `to` for the variable names I could write the call as:

```
self.transfer(from, to)
```

On a more general note, I can see how the change aims to improve safety at the cost of convenience. I'm not 100 % sold if we should adopt it but I'm generally open to the idea.

**Comment by sbillig** [comment]
> Wouldn't it be reasonable to not require the labels if the variable name matches the argument name.

Yeah, totally. That's how I've implemented required named args in struct and event constructors (inspired by rust, of course):
![Screenshot from 2021-05-25 05-49-49](https://user-images.githubusercontent.com/50669/119500954-38d33880-bd1d-11eb-8f42-4e5c0dc66157.png)

(named args were required for struct constructors; I extended that to events)

**Comment by cburgdorf** [comment]
Yes, I'm on board as long as we continue to not require named arguments if the parameter names already match the argument name :+1:

**Comment by Y-Nak** [comment]
Yeah, I completely agree.
