### ISSUE TITLE
Start language specification

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#40]
We will need to write a specification so that it's possible to audit this project. It would also just be useful to have in general for ourselves and for users.

This is the [specification](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) for c++. It might help give us an idea of how our specification should be structured.

For this issue we should do two things:
- [x] create a new directory named *spec* with an empty README 
- [x] create a couple issues for things that can be easily specified at the moment

**Comment by cburgdorf** [comment]
Throwing in the [Rust reference](https://doc.rust-lang.org/stable/reference/introduction.html) (Not to be confused with the [Rust book](https://doc.rust-lang.org/book/) or [Std library docs](https://doc.rust-lang.org/stable/std/index.html) ) as another good example. Even though they mention it is not 100 % the specification but the closest thing to a specification that exists today.

>Finally, this book is not normative. It may include details that are specific to rustc itself, and should not be taken as a specification for the Rust language. We intend to produce such a book someday, and until then, the reference is the closest thing we have to one.

**Comment by cburgdorf** [comment]
For reference: We have an [early draft](https://github.com/ethereum/fe/blob/master/spec/index.md) in master. Basic structure / system is heavily influenced by the [Rust reference](https://doc.rust-lang.org/stable/reference/introduction.html)
