### ISSUE TITLE
Support dynamically sized return values when calling external contracts.

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#405]
See discussion on #321:

# "
Yes, this is on the right track.

It boils down to the fact that we don't know how much memory will be used in the call return for dynamically sized types. It's not necessarily a bug, just a missing feature that is not handled well.

`call(g, a, v, in, insize, out, outsize)`

> call contract at address a with input mem[in…(in+insize)) providing g gas and v wei and output area mem[out…(out+outsize)) returning 0 on error (eg. out of gas) and 1 on success

See the Yul [docs](https://docs.soliditylang.org/en/latest/yul.html#evm-dialect).

I see two possible solutions:
1. We add a `max_size` value to `AbiType` and use that instead of this `static_encode_size` function. We of course know the max size of `string3`, since the type is bounded. One drawback to this is that we'll have trouble dealing with external contracts imported using their JSON ABIs, since dynamically sized types have no bounds there. It would definitely work in the short-term, tho.
2. We set a very high `outsize` and then only allocate what's used. I'm not quite sure if `outsize` influences memory access gas costs :thinking:.

I think for now we should just go with (1), since importing external contracts using their json ABIs is not happening anytime soon.
# "

**Comment by hrkrshnn** [comment]
Why not set out and outsize to 0 and use returndatacopy to copy the value to memory? Do you need to statically know all the memory writes?

**Comment by g-r-a-n-t** [comment]
@hrkrshnn you're right. I didn't realize the returndata copy/size opcodes existed until digging into the issue more. I'm using them in the [PR](https://github.com/ethereum/fe/pull/415/files#diff-61085c35cb2069034ab3f8277d67935a6cb5610f12e9a585ca5d4f6c8aa82c14R74) for this.
