### ISSUE TITLE
Allow pass statement on contract level

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#407]
### What is wrong?

I think that the `pass` statement should be allowed on the contract level. Currently it is only allowed on the function level.
The following code is illegal:

```
contract GuestBook:
    pass
```

### How can it be fixed

Start by teaching the parser to accept `pass` here and then follow the rabbit

**Comment by g-r-a-n-t** [comment]
I guess the alternative is

```
contract GuestBook
```

I'm also wondering if we want to follow the same convention for zero-sized types:

```
struct Empty

# or

struct Empty:
  pass
```

I'm having a hard time deciding which one looks nicer.

**Comment by cburgdorf** [comment]
Good thinking. Initially I thought `struct Empty` would be nice but now that I think about it a bit more I think this feels a bit more Pythonic (Feonic?)

```
struct Empty:
  pass
```

Especially when one thinks about `pass` with `def` and `contract`. Why would those work with `pass` but empty structs wouldn't. It feels like we would be introducing a weird special case. So, my vote is on `pass`.

**Comment by g-r-a-n-t** [comment]
sounds good. Im going to implement zero-sized types for #406 this way

**Comment by g-r-a-n-t** [comment]
we also probably want these on events. I can add them all in #406

**Comment by cburgdorf** [comment]
>we also probably want these on events

Makes sense
