### ISSUE TITLE
More descriptive error message for CannotMove error

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#408]
### What is wrong?

The following snippet returns `self.messages[addr]` without calling `to_mem()`

```
contract GuestBook:
  messages: map<address, bytes[100]>

  pub def get_msg(addr: address) -> bytes[100]:
      return self.messages[addr]
```

The error message isn't very user friendly.

```
Unable to compile guest_book.fe.
Analyzer error: CannotMove on line 8
pub def get_msg(addr: address) -> bytes[100]:
      return self.messages[addr]
```

### How can it be fixed

The error message should explain and hint towards `to_mem()` possibly even linking to http://fe.ethereum.org/docs/spec/index.html#623-the-to_mem-function

**Comment by sbillig** [comment]
I can fix this as part of #398. I originally intended to just hook up the codespan machinery and use it for new checks (for now), but I've been converting some of the existing error cases.

**Comment by sbillig** [comment]
Here's the first draft. Verbiage suggestions heartily welcomed. The latter error is emitted by `assignable_expr`, so it's not specific to return values (though it could be with some refactoring).

![Screenshot from 2021-05-14 21-35-10](https://user-images.githubusercontent.com/50669/118348044-62f65080-b4fc-11eb-9ce3-21071a54333c.png)

**Comment by sbillig** [comment]
The use of the word "value" here doesn't jibe with the "value type" vs "reference type" dichotomy, but I couldn't think of a better word. The solidity docs refer to "values of reference type", so apparently they couldn't either.
