### ISSUE TITLE
Public functions aren't actually callable from external accounts

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#418]
### What is wrong?

Consider the following Fe code

```
contract Bar:

  pub def foo() -> u256:
      return 50
```

If we deploy that contract, we should expect to be able to make a *call* (**not** sending a transaction) to the deployed contract and get the value `50` returned. That is however not the case.

We can send a *transaction* that calls `foo()` and we can in fact see that the call returns `50` but the same doesn't work for a simple call even though it should.

Here is a transaction to a deployed Görli contract that demonstrates the foo call as a sent transaction (which is of course a waste of gas for what is supposed to be a readonly call).

https://goerli.etherscan.io/vmtrace?txhash=0x712e4c38148971e6d088fb66ff79590f6024e8836392085993faef7d0c25a356&type=parity

![image](https://user-images.githubusercontent.com/521109/119539112-20e6cd80-bd8c-11eb-8868-b624d22179d1.png)

But if you try to simple *call* `foo()` on the contract `0xf1500f97a02673e17304636fbbceab5816c64386` you won't get any data returned.

I think none of our tests detect this because our test suite *always* sends transactions even if we are just calling *readonly* APIs.

### How can it be fixed

Investigate

**Comment by g-r-a-n-t** [comment]
How did you make the `call`?

**Comment by cburgdorf** [comment]
I'm using DappTools:

Here's a call to a similar contract written in Solidity that works:

```
$ ETH_RPC_URL=http://goerli-geth.dappnode:8545 seth call 0x8b7f0bd34e3e860b3a7080e6b7b8bb232a929c6f "foo()"
0x0000000000000000000000000000000000000000000000000000000000000032
```

But it actually just got a bit weirder. See, this is where I originally tried to call `foo()` on `0xf1500f97a02673e17304636fbbceab5816c64386` which is written in Fe. It gave me no output.

![image](https://user-images.githubusercontent.com/521109/119546748-8dfe6100-bd94-11eb-9c9b-3ca3e32656f8.png)

In fact, I could call any method and no matter if it existed or not it would always return success with no data.

But now I tried it again and it actually works...

![image](https://user-images.githubusercontent.com/521109/119546850-ab332f80-bd94-11eb-90ac-ba08cf70448d.png)

And I wonder if that has something to do with the fact that I made *send* a transaction to `foo()` before or if I'm taking crazy pills.

Let me re-deploy the contract and try it again...

**Comment by g-r-a-n-t** [comment]
haha, I'll give it a shot myself and see what happens.

**Comment by cburgdorf** [comment]
Ok, I redeployed the contract and the `foo()` call seems to work now...so weird. I don't know what happened. I'll try to continue with the functionality that I actually wanted to test and see if it gets weird again...

**Comment by cburgdorf** [comment]
Maybe what happened is that I was seeing the deployed contract on etherscan but my node fell behind the tip and didn't have it yet. Not sure if that would mean the call would return with success and empty data but that's the only reasonable explanation I can think of.

**Comment by cburgdorf** [comment]
Ok, the `get_msg` call works, too.

![image](https://user-images.githubusercontent.com/521109/119552118-a83b3d80-bd9a-11eb-93ca-36a9571683e5.png)

I will close this. My best guess is that it was a weird coincidence of my personal node falling behind the tip when I tried it and working properly when I tried the solidity example. Nothing to see here...maybe :man_shrugging:
