### ISSUE TITLE
Remove user-facing `todo`s and `unimplemented`s

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#436]
### What is wrong?

The compiler will crash during analysis of features that are not yet implemented. For this reason, we have been filtering out crashes that display the text "not implemented" or "not yet implemented" when fuzzing. This would be fine if we didn't also use these panic messages in later stages of compilation, but we are, and it's likely that we've been filtering out meaningful crashes.

### How can it be fixed

- replace all justifiable `todo`s and `unimplemented`s with graceful analyzer errors
- let agroce know that any panic is considered a bug

**Comment by g-r-a-n-t** [comment]
filtering out certain panics is no longer necessary @agroce

**Comment by agroce** [comment]
Ok!  It may take me a day or two to restart the fuzzer instances with the latest source, but I'll put them on the "no holds barred" task before too long.

**Comment by agroce** [comment]
Hmm.  On latest github, I get:

```
target/debug/fe tests/src/lowering/fixtures/nested_tuple.fe
thread 'main' panicked at 'not yet implemented', compiler/src/lowering/names.rs:38:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

so there are still "not implemented"s -- I assume bug reportable, though?
