### ISSUE TITLE
Make --optimize the default

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#439]
### What is wrong?

Optimization is currently opt-in via `--optimize`. Unoptimized Fe code is virtually impractical to deploy and use so we should make that the default.

### How can it be fixed

- Decide on how to handle the CLI args (sorry, this is just a quick weekend brain dump)
- :hocho:

**Comment by mjobuda** [comment]
sent pull request

**Comment by cburgdorf** [comment]
This landed
