### ISSUE TITLE
Use let keyword for variable declarations

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#501]
### What is wrong?

Currently variables are declared like this:

```
val: bool = true
```

In the future we can assume to add some form of type inference so that the above code would be shortened to:

```
val = true
```

In that form there is nothing to distinguish a variable declaration from other assignments. In other words, these two lines look identical even though the first line declares the variable `var` whereas the second line assigns it a new value.

```
val = true
val = false
```

Making variable declarations more explicit seems in line with the goals of the language. Furthermore, in the future we likely want to make variables immutable by default which is yet another reason to follow Rusts lead with `let val = true` and `let mut val = true` syntax.

### How can it be fixed

Require variable declarations to use the `let` keyword.

Example:

```
let val: bool = true
```

**Comment by sbillig** [comment]
Implemented in #509
