### ISSUE TITLE
Tokenizer calculates spans off by one

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#53]
### What is wrong?

Given the following code:

https://github.com/ethereum/fe/blob/8d05a906cfe56a43e190c827b8dbef55af9c8b15/compiler/tests/fixtures/guest_book.vy#L1-L15

The tokenizer calculates these tokens.

```
[Token {
    typ: NAME,
    string: "type",
    span: Span {
        start: 0,
        end: 4
    },
    line: "type BookMsg = bytes[100]\n"
}, Token {
    typ: NAME,
    string: "BookMsg",
    span: Span {
        start: 5,
        end: 12
    },
    line: "type BookMsg = bytes[100]\n"
}, Token {
    typ: OP,
    string: "=",
    span: Span {
        start: 13,
        end: 14
    },
    line: "type BookMsg = bytes[100]\n"
}, Token {
    typ: NAME,
    string: "bytes",
    span: Span {
        start: 15,
        end: 20
    },
    line: "type BookMsg = bytes[100]\n"
}, Token {
    typ: OP,
    string: "[",
    span: Span {
        start: 20,
        end: 21
    },
    line: "type BookMsg = bytes[100]\n"
}, 
...
```
[Read full source](https://gist.github.com/cburgdorf/a04e1f3a23603f2b329ca3d50616a200)

It is placing "type" from `0..4` which is correct but then it puts `BookMsg` from `5..12` which actually spans ` BookMs` (from the leading whitespace up to the `s`, missing out the `g`.

### How can it be fixed

It looks like it is miscalculating the whitespace somewhere but I did not dig in further.

**Comment by sbillig** [comment]
No longer an issue. The new tokenizer gets this right, and I think the old tokenizer did too when it was replaced. (5..12 is actually right for BookMsg, fwiw, so maybe this was never an issue?)
