### ISSUE TITLE
Add a special `__call__` function

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#559]
Users can define a contract function named `__init__` that will execute at initialization time.

Continuing with this pattern, we might consider adding a function named `__call__` that runs at *call time*. By adding such a function, the language would be more flexible with regard to contract interfaces.

e.g.

```python
contract Foo:
  # the __call__ function is defined with full access here. not sure if that should be required..?
  pub fn __call__(mut self, ctx: mut Context):
    # grab the calldata from the Context object
    let calldata = ctx.calldata()

    # the function is selected using the first byte in calldata
    if calldata[0] == 0:
      # pass the second byte into foo
      self.foo(calldata[1])
      return
    else if calldata[0] == 1:
      # pass the second and third byte into bar
      self.bar(calldata[1], calldata[2])
      return
   
    revert "invalid calldata"

  fn foo(self, my_byte: u8):
    # do stuff

  fn bar(self, my_byte: u8, my_extra_byte: u8):
    # do stuff
```

In the example above, we have defined a super simple and efficient contract interface. Writing a custom interface such as this one might be useful for people looking to reduce fees. The other benefit is that we could move the Solidity ABI decoding/encoding implementation into Fe-lang as opposed to having that code generated in the Yul gen phase.

In the future, it might be possible to change the interface of a contract using a procedural macro that writes a `__call__` function for you.

e.g.

```python
#[interface(SomeAbi)]
contract Foo:
   ...
```

One thing to note is that the `__init__` function takes ABI encoded parameters, which does not align well with this proposal.

**Comment by cburgdorf** [comment]
In the example above, how is `__call__` being triggered? Does it run like a hook whenever a public function is called (the above example has none except `__call__`) or is it called manually like `Foo.__call__()`? In that case, I'd be wondering what is the special role of it since a user could have just defined it as a regular function and e.g. call `Foo.dispatcher()`.

**Comment by g-r-a-n-t** [comment]
> how is __call__ being triggered?

The `__call__` function is the only thing that would be triggered when the contract is called, so any `pub` labels become obsolete.

If one does not define a call function, then a `__call__` that performs Solidity ABI dispatching would be added to the contract during lowering.

**Comment by g-r-a-n-t** [comment]
Also note that `Foo.dispatcher()` would be selected using the Solidity ABI, which means that custom dispatching has not been defined.

The idea is to provide total flexibility around contract interfaces and allow for us to define the existing interface in Fe-lang

**Comment by cburgdorf** [comment]
Oh, now I understand. Genius! I like that :+1:
