### ISSUE TITLE
Implement a method to transfer wei

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#567]
### What is wrong?

There's currently no way to transfer Wei in Fe.

### How can it be fixed

After reading [this](https://gist.github.com/karmacoma-eth/4f206a46dedc6da6808c1ccdef3262d0) and [that](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/) I'm of the opinion that we should create a builtin function that should roughly translate into the following YUL code:

```
call(gas(), to_address,  value_in_wei,  0, 0, 0, 0)
```

Possible naming candidates:

- `send_wei`,
- `send_value` (similar to the OpenZeppelin function that [works the same way](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol#L54))

Example:

```
pub def burn():
  send_wei(address(0x), 1000)
```

Or in the future when #558 is implemented it would be:

```
pub def burn(ctx: mut Context):
  ctx.send_wei(address(0x), 1000)
```

**Comment by g-r-a-n-t** [comment]
`send_value` and copying what openzepplin did sounds good to me. The `send` and `transfer` methods can always be exposed as unsafe.
