### ISSUE TITLE
Analyzer doesn't check unary minus operation on unsigned type

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#651]
### What is wrong?
```python
contract Foo:
    pub fn bar(self) -> u32:
        let unsigned: u32 = 1
        return -unsigned
```

It's better to reject the code above for safety.

### How can it be fixed
Tweaking [this lines](https://github.com/ethereum/fe/blob/50443ebbf15ceb567d592fcab8f0ccee96d4355b/crates/analyzer/src/traversal/expressions.rs#L762-L777) would fix the issue.

**Comment by hmrtn** [comment]
I'd like to tackle this issue.

**Comment by Y-Nak** [comment]
Thanks @hmrtn! Please feel free to ask me in Discord or here if you have any questions.
