### ISSUE TITLE
Add key differences to solidity to readme

### ISSUE THREAD

**Issue by jtraglia** [ethereum/fe#673]
### What is wrong?

The first question I get when I tell people about Fe is "how is Fe different than Solidity?" I believe the readme should clearly list some of the key differences between it and Solidity. In other words, why should I use Fe instead of Solidity? The "features & goals" section is good, but a newcomer might not understand what makes it special.

There could be a political problem in calling out Solidity. If so, feel free to ignore this issue.

### How can it be fixed

Add a list of key differences between Fe and Solidity to the readme.

**Comment by cameel** [comment]
> There could be a political problem in calling out Solidity. If so, feel free to ignore this issue.

As a Solidity team member, I think I can safely say - don't worry :) We're cool with an objective comparison even if it points out shortcomings in the language. We're well aware of many and constantly working on improving it. Just please make it fair and be sure you're comparing latest releases and not latest Fe with ancient Solidity :)
