### ISSUE TITLE
Set function access in Json ABI based on presence of `ctx` and `self` parameter

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#678]
### What is wrong?

As noted in #638, [`FunctionSignature`](https://github.com/ethereum/fe/blob/766d44c9fd1e88509b7539f5b69be766bb7043f4/crates/analyzer/src/namespace/types.rs#L156-L161)s now include a `ctx_decl` attribute. If both the `ctx_decl` and `self_decl` attributes are `None`, then we can mark it as a pure function in the [Json ABI](https://github.com/ethereum/fe/tree/766d44c9fd1e88509b7539f5b69be766bb7043f4/crates/abi/src).

example:

```
contract Foo:
  # this should be marked as pure
  pub fn add(a: u256, b: u256):
    pass
```

### How can it be fixed

:keyboard:

**Comment by Y-Nak** [comment]
This will be resolved in #676
