### ISSUE TITLE
Allow `pub unsafe fn __call__`, and `pub unsafe fn` for contract fns in general

### ISSUE THREAD

**Issue by sbillig** [ethereum/fe#687]
### What is wrong?

> a contract function can be either `pub` or `unsafe`, but not both

^ This seems like a restriction that we can drop. :shrug:

**Comment by dalmoveras** [comment]
Hey @sbillig  could you provide more details please?

**Comment by sbillig** [comment]
@dalmoveras There's currently a check that disallows public contract functions from being unsafe; for example:
```
contract Foo:
  pub unsafe fn bar():
    std::evm::mstore(0, 100)
```

IIRC, I chose to do this because `unsafe` functions should only be callable from an `unsafe` context (another unsafe fn or an unsafe block), but public contract functions can be called from any external contract, and thus we can't restrict how they're called.

In hindsight, it doesn't seem useful to disallow `pub unsafe`.

Changing this is probably as simple as removing this block of code: https://github.com/ethereum/fe/blob/master/crates/analyzer/src/db/queries/functions.rs#L30-L39 and updating or removing a test or two.
