### ISSUE TITLE
Why package it into a new language？

### ISSUE THREAD

**Issue by Jzow** [ethereum/fe#706]
I have read the documents. Many of them are the features of rust. I don't understand the purpose of doing so. Smart contracts can be written in rust

**Comment by Jzow** [comment]
I'm sorry if  disturbed, because I just don't understand why. I read the home page to say that it combines **Python** and **Rust**

**Comment by g-r-a-n-t** [comment]
Hi, thanks for the question. How might one compile Rust to EVM and how is the development experience?
