### ISSUE TITLE
Improve parser error message

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#71]
### What is wrong?

Parsing code that isn't yet supported leaves one with an error that just says "Parser error". E.g. the snippet from #59 is such a candidate.

```
contract Foo:
    pub def bar() -> u256:
        return 0
```

### How can it be fixed

We drop all previous error information from the `ParseError` here:

https://github.com/ethereum/fe/blob/5b9d302cef06595c6c76486415c6a109e899cb99/compiler/src/errors.rs#L46-L50

However, there's not really a good error message from the parser that we could display so I guess we would have to start there to improve the errors.

**Comment by cburgdorf** [comment]
I've put this on the next milestone but I think its coming with one @g-r-a-n-t next PRs

**Comment by g-r-a-n-t** [comment]
closed in #140
