### ISSUE TITLE
Remove `event` type and keyword

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#717]
Currently, we use `event` type defined with `event` keyword to emit an event.
But actually, we could handle `event` types in the same way as types defined with the `struct` keyword, i.e., normal user-defined struct. 
The only difference between `event` and `struct` would be `topic`, so it would be necessary to introduce some special syntax or language features that enable it to be specified.

Currently, I'd like to propose allowing `@[indexed]` or `@[topic]` attribute in the field like below.
```python
struct MyEvent:
    @[indexed]
    x: i32

    y: i32
```

In the short-term plan, we could treat `@[indexed]` attribute specially, then generalize the attribute feature in the long-term plan.

**Comment by distractedm1nd** [comment]
What effect does this have (or would it have in the future) on indexed fields?

**Comment by cburgdorf** [comment]
>In the short-term plan, we could treat @[indexed] attribute specially, then generalize the attribute feature in the long-term plan.

I agree we should do this. This is basically the only thing holding us back from adding an `emit<T: Event>(val: T) {..}` message directly on `context.fe` in the std lib.

**Comment by cburgdorf** [comment]
> What effect does this have (or would it have in the future) on indexed fields?

I think the main advantages of treating events as structs are:

1. Less special syntax
2. Code re-use (e.g. being able to use the a `Foo` struct for foo things and just happen to also emit it as an event)
3. Flexibility. If events are just structs, chances are people can come up with nice little helper libraries down the road

**Comment by Y-Nak** [comment]
#772
