### ISSUE TITLE
Nested maps

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#77]
We should be able to support maps of the form: `map<address, map<address, u256>>`

My thinking is that the storage location for the final value (`u256` in this case) should be found like so:

```
self.foo[0x00][0x01]
|------|
    0.) storage index
|------------|
       1.) intermediary storage index
|------------------|
         2.)  storage location of value
```

The expression attributes for each of the above would be as follows:
0.) `type: Map<...>, location: Storage { index: n }` 
1.) `type: Map<...>, location: Storage { index: 0 }` with the *real* index being determined during runtime `keccak256(n, 0x00)`
2.) `type: u256, location: Value`  

*Note: This is a bit strange in that we are using what would normally be a pointer to a segment in storage (`self.foo[0x00]`) as a new storage index. I don't see a problem with this though.*

**Comment by cburgdorf** [comment]
Just in case you haven't read this yet, I found this to be a great read on the topic: https://programtheblockchain.com/posts/2018/03/09/understanding-ethereum-smart-contract-storage
