### ISSUE TITLE
compile `solc` error in Mac(m1)

### ISSUE THREAD

**Issue by aisuosuo** [ethereum/fe#771]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/28430113/180351218-858bab45-2344-47a6-9305-4a0881ecc6c8.png">

i have installed boost.

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/28430113/180351407-a11885a5-808e-4089-b7bb-331b225f1fa3.png">

**Comment by cburgdorf** [comment]
Do you also have `libboost-all-dev` installed`?
Here is what our CI is doing for Mac support:

https://github.com/ethereum/fe/blob/7740c69d20800bb294728664777913c0c6c0ba2c/.github/workflows/main.yml#L81-L88

**Comment by aisuosuo** [comment]
> Do you also have `libboost-all-dev` installed`? Here is what our CI is doing for Mac support:
> 
> https://github.com/ethereum/fe/blob/7740c69d20800bb294728664777913c0c6c0ba2c/.github/workflows/main.yml#L81-L88

how to install in mac m1?

**Comment by aisuosuo** [comment]
> It works fine in my environment (Mac M2). Could you please type `brew info boost` and share the result?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/28430113/180907242-7325c335-6b3f-42e2-beb7-b1d0fc9879dd.png">

**Comment by aisuosuo** [comment]
@Y-Nak  Did you find the problem?

**Comment by 0xalpharush** [comment]
I'm also running into this issue after installing boost via brew and confirming its installation with `brew info boost`.

**Comment by brockelmore** [comment]
This issue arises due to this: https://earthly.dev/blog/homebrew-on-m1/

in tandem with: https://github.com/Y-Nak/solc-rust/blob/f18b1cec1996feb2a361c616f333507bcfc5be76/build.rs#L41

The build script explicitly specifies *where* to search for static libraries

**Comment by sbillig** [comment]
Nice, so adding `println!("cargo:rustc-link-search=native=/opt/homebrew/lib/");` to build.rs should fix it. Could someone with an M1 test this?
