### ISSUE TITLE
Reject invalid `pub` in a `struct` definition

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#787]
### What is wrong?
Currently, an invalid `pub` appearance is not rejected, e.g.,
```rust
pub struct Bar {
    pub x: i32
pub}
```

### How can it be fixed

Tweaking the below code will resolve the issue.
https://github.com/ethereum/fe/blob/1190d93ef644d4e993497bf27ce5a48068c872ba/crates/parser/src/grammar/types.rs#L28-L55

**Comment by shraddhafalane** [comment]
Would like to take a look on it.
