### ISSUE TITLE
Possible introduction of prefix keywords or qualifiers

### ISSUE THREAD

**Issue by davesque** [ethereum/fe#8]
There are a lot of situations where Rust Vyper could emulate Python Vyper's syntax, but it seems sub-optimal to do that because Python Vyper's syntax seems to have been designed mostly to accommodate the Python parser.

From the point of view of Rust Vyper, it seems more and more like the Python parser is underpowered because it was designed for a dynamic language in which methods and variables don't require much annotation.  This is because there aren't many restrictions on how methods and variables can be used in Python.

Here's a concrete example.  If Rust Vyper followed Python Vyper's syntax, here are two different ways that things would be annotated to indicate that they're "public":
```
contract GuestBook:
    guest_book: public(map[address, bytes[100]])

    @public
    def sign(book_msg: bytes[100]):
        ...
```
Frankly, this is ugly and here are some reasons why:
* Storage variables and methods are being annotated in two entirely different ways.  Storage variables use something like a "pseudo-function" called `public` that "returns" a new type `public(map[address, bytes[100]])`.  On the other hand, methods use the python decorator syntax.  Public methods are annotated by placing a `@public` directive on the line preceding the method declaration.
* Being forced to use the pseudo-function syntax for variable annotations means that having more than one annotation (if we ever want a feature like that) makes things very unreadable and forces the inclusion of lots of nested parentheses.

Now consider this alternative syntax:
```
contract GuestBook:
    pub guest_book: map[address, bytes[100]]

    pub def sign(book_msg: bytes[100]):
        ...
```
In my opinion, this is far more readable for the following reasons:
* Both property and method annotations use *the same* syntax.
* The annotations are at the front of the line where they are most visible.
* The keyword "pub" is shorter but no less expressive.

It seems like we could also elect to keep the decorator syntax in case we also want modifiers (which are a feature that I think was unfairly excluded from Vyper).  But the qualification of a method as public or not could use a prefix keyword on the line of the method declaration.

**Comment by davesque** [comment]
By the way, just to head off this discussion if it happens, I'm aware that there's really no difference in Python semantically between the `public(...)` syntax and the `@public` syntax.  The latter is just syntactic sugar for application of a decorator to a function object which could also be done by using the function call syntax `public(...)`.  However, in Vyper, these semantics are irrelevant and shouldn't inform any design decisions about the syntax.

**Comment by cburgdorf** [comment]
100 % agree on your proposal to be the nicer syntax. Shortening `public` to `pub` might be the most controversial about that idea but that's also just a tiny nuance of the proposal (I tend to like `pub` simply because it saves a bit horizontal screen space).

I also believe that this project should not restrict itself to the python-vyper syntax too much if there's a clear benefit to going with a different syntax which I think is the case here.

**Comment by pipermerriam** [comment]
Same thoughts as Christoph

**Comment by pipermerriam** [comment]
Are you thinking that decorators would still be part of the language?

**Comment by davesque** [comment]
> Are you thinking that decorators would still be part of the language?

Yes, I had thought that there might still be a use for a kind of long-form annotation syntax in which annotations could be listed off one line at a time before a method definition.  I've also had the idea of re-introducing the Solidity modifier feature into Vyper and, if that happened, it seems the most natural way to list off modifiers would be like decorators in Python.
