### ISSUE TITLE
“fe_mac” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by pedrommaiaa** [ethereum/fe#800]
### What is wrong?

can't run `./fe_mac -h`

<img width="254" alt="Screen Shot 2022-10-14 at 2 14 14 PM" src="https://user-images.githubusercontent.com/100535780/195913807-ddf9ebb6-7f31-4f2d-9999-0a77b303d785.png">

**Comment by cburgdorf** [comment]
Sorry, I'm on mobile but this might help to get around the error.

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by pedrommaiaa** [comment]
I gave permission the first time but for some reason it didn't work, after downloading it again and running `chmod +x fe_mac` again it worked!
