### ISSUE TITLE
 Bracket Error

### ISSUE THREAD

**Issue by edmiikk** [ethereum/fe#845]
### What is wrong?
``` console 
$ RUST_BACKTRACE=full fe build main.fe --overwrite
```
<code>thread 'main' panicked at 'not yet implemented', crates/parser/src/parser.rs:74:25
stack backtrace:
   0:     0x562feb1bc1a0 - <unknown>
   1:     0x562feb1d972e - <unknown>
   2:     0x562feb1b9145 - <unknown>
   3:     0x562feb1bda93 - <unknown>
   4:     0x562feb1bd77f - <unknown>
   5:     0x562feb12453c - <unknown>
   6:     0x562feb1be1dd - <unknown>
   7:     0x562feb1bdff1 - <unknown>
   8:     0x562feb1bc64c - <unknown>
   9:     0x562feb1bdd52 - <unknown>
  10:     0x562fea47ba03 - <unknown>
  11:     0x562fea47b8cd - <unknown>
  12:     0x562feb0f6c8b - <unknown>
  13:     0x562feb0e90c2 - <unknown>
  14:     0x562feb0e55ca - <unknown>
  15:     0x562feb0e5120 - <unknown>
  16:     0x562feb0e3f79 - <unknown>
  17:     0x562feb0def55 - <unknown>
  18:     0x562feb110746 - <unknown>
  19:     0x562feb110056 - <unknown>
  20:     0x562feb0df6fb - <unknown>
  21:     0x562feafdfe2e - <unknown>
  22:     0x562feafb8bc5 - <unknown>
  23:     0x562feb0366eb - <unknown>
  24:     0x562feb08cc21 - <unknown>
  25:     0x562feaf7f132 - <unknown>
  26:     0x562feaed9b3e - <unknown>
  27:     0x562fea518de3 - <unknown>
  28:     0x562feaea8757 - <unknown>
  29:     0x562feaea86c5 - <unknown>
  30:     0x562fea4e36ec - <unknown>
  31:     0x562fea4d8759 - <unknown>
  32:     0x562fea4ae713 - <unknown>
  33:     0x562fea4b0ef3 - <unknown>
  34:     0x562fea4b5229 - <unknown>
  35:     0x562feb1b484f - <unknown>
  36:     0x562fea4af2f8 - <unknown>
  37:     0x7fe3a6189d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  38:     0x7fe3a6189e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  39:     0x562fea4928be - <unknown>
  40:                0x0 - <unknown>
</code>

### Source
Offending line:

<code>assert (isTopLevelCall and self._initialized < 1)),"Initializable: contract is already initialized"</code>

### How can it be fixed
Work around is to drop the offending bracket
<code>assert (isTopLevelCall and self._initialized < 1),"Initializable: contract is already initialized"</code>

**Comment by Y-Nak** [comment]
Thanks for opening the issue.
This will be fixed in [fe-v2](https://github.com/ethereum/fe/pull/840).

**Comment by edmiikk** [comment]
Domo arigato Nakanishi san.

**Comment by Y-Nak** [comment]
Doitashimashite
