### ISSUE TITLE
v2 parser AugAssign stmt doesn't allow `x[0] += 1`

### ISSUE THREAD

**Issue by sbillig** [ethereum/fe#875]
### What is wrong?

The new parser (v2 branch) only supports augmented-assignments where the LHS is an identifier. Eg `x += 1` is supported, but `x.y += 1` isn't.

### How can it be fixed

Good opportunity for someone to become familiar with the new parser, I guess.

**Comment by Y-Nak** [comment]
If anyone is interested in this issue, please fork from [`Hir`](https://github.com/ethereum/fe/pull/860) PR because I modified the parser in the PR.

**Comment by Y-Nak** [comment]
It also seems necessary to fix the Assign statement, which wrongly assumes that its left-hand side is a pattern. 
lhs should be a pattern or expression.

**Comment by EmanuelCorsino** [comment]
If v2 parser alows probe .smt insted of .stmt by using an incluide ...  .smt.create.stmt":::::" meany that solve the problem.. find in your languague obviusly

**Comment by Y-Nak** [comment]
Resolved in https://github.com/ethereum/fe/pull/985
