### ISSUE TITLE
Support for call expressions with parameters

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#89]
### What is wrong?

After https://github.com/ethereum/fe/pull/78 lands, Fe will have support for call expressions (e.g. `return self.foo()`). However it does not handle yet call expressions with arguments such as `return self.foo(42)`. We need to implement that.

### How can it be fixed

Probably drilling deeper into what https://github.com/ethereum/fe/pull/78 does :sweat_smile:

**Comment by g-r-a-n-t** [comment]
I'm going close #88 and move this under the erc20 milestone.

We should also probably create a separate issue for call statements.
