### ISSUE TITLE
`std::evm` functions should take buffer types

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#891]
### What is wrong?

A number of functions defined in [std::evm](https://github.com/ethereum/fe/blob/master/crates/library/std/src/evm.fe) take offsets and lengths for regions of memory and calldata. These should take [buffer](https://github.com/ethereum/fe/blob/master/crates/library/std/src/buf.fe) types instead.

### How can it be fixed

- implement `CalldataBuffer`, `CalldataBufferReader`
- update `revert_mem`, `return_mem`, `call_data_copy`, `code_copy`, `ext_code_copy`, `keccak256_mem`, `create`, `create2`, `call`, and `log` 

run `$ cargo test std_lib` to check changes made to `crates/library`

**Comment by Hrushi20** [comment]
Hey, can I work on this issue? Can you give me a brief idea about `CalldataBuffer` and `CalldataBufferReader`, so that I can start working on this issue.

**Comment by g-r-a-n-t** [comment]
hey sorry for the late reply @Hrushi20

this work has been completed, but I could help you find another task if you're interested

**Comment by Hrushi20** [comment]
Hey! I'm interested. Any beginner friendly issues I can get started with?

**Comment by g-r-a-n-t** [comment]
would you be interested in adding support for the transient storage opcodes?

**Comment by g-r-a-n-t** [comment]
here, just wrote an issue https://github.com/ethereum/fe/issues/978
