### ISSUE TITLE
Add `usize` and `isize` as a primitive type

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#995]
We don't have `usize` and `isize` to represent target-dependent pointer-size, which are useful, especially for
1. Memory Indexing: `usize` is primarily used for indexing into collections and working with memory sizes.
2. System Compatibility: Both `isize` and `usize` provide a means to write code that is portable across systems.

This issue can be split up into several phases.
* [x] Modify the parser to accommodate these types
* [ ] Make name resolution handle them properly as a builtin type
* [ ] Make type check handle them. These types will affect other built-in types, e.g., array type definition.

**Comment by lana-shanghai** [comment]
Hey, could I work on this? @Y-Nak

**Comment by Y-Nak** [comment]
Yes, of course!

**Comment by lana-shanghai** [comment]
> Yes, of course!

Sweet! So this task includes mentoring from you? :) if you have any guidance on how to start with the parser, please share, otherwise I am diving into the codebase for now!

**Comment by Y-Nak** [comment]
> So this task includes mentoring from you?

yep!

> if you have any guidance on how to start with the parser

Sorry, I made the wrong description for the issue; you don't need to modify the parser. So, the first step for this issue would be to make the name resolution handle the two types properly.

The concrete steps would be
1. Add `usize` and `isize` to`hir::hir_def::ident::kw`.
2. Modify `hir::hir_def::prim_ty` to accommodate those two types(`IntTy` and `UintTy` are the places where you would need to modify).
3. Modify `hir::hir_def::PrimTy::all_types` so that it includes the newly added `usize` and `isize` in step 2.

**Comment by Y-Nak** [comment]
For the type checker module, the steps would be
1. Modify `hir_analysis::ty::ty_def::PrimTy`.
2. Modify `impl From<HirPrimty> for TyBase` in `ty_def` module.

In addition to that, you probably need to modify some auxiliary methods like `ty_def::PrimTy::is_integral`.

Basically, that'd be all necessary things(I might miss something, though).
Please feel free to ask any questions.

**Comment by Y-Nak** [comment]
Oh, currently, the head of `v2` is https://github.com/ethereum/fe/pull/1007, which will be merged soon. 
Please use that branch as a base.

**Comment by Y-Nak** [comment]
resolved in #1012
